### PR TITLE
v740sp02

### PR DESCRIPTION
**Pull request by larshp**
not to be merged, just for getting list of errors

### CODE REVIEW

**Comment by nununo** [comment]
Great. Thanks! I'll look into these as soon as I have some time.

**Comment by larshp** [comment]
if you set "require branches to be up to date" in the branch protection, its easy to pull the latest changes from main branch in to this branch

**Comment by nununo** [comment]
Hi Lars,

I am finally having a little time to dedicate to abapTimeMachine. I noticed you closed this so I replicated it in another branch so that I can go through the list of linter errors and deal with them. But to be honest I'm having a hard time making sense of any of them.

Here it is: https://github.com/abapinho/abapTimeMachine/pull/129/files?diff=unified&w=0

None of them seem to make sense to me, though.
I wonder if I'm doing something wrong. For example, the very first one says this:

Check failure on line 140 in src/zcl_timem_diff.clas.abap

 <https://github.com/abapinho/abapTimeMachine/pull/129/checks?check_run_id=12027688923>
abaplint
/ abaplint

Statement does not exist in ABAPv740sp02(or a parser error), "result"
https://rules.abaplint.org/parser_error

about this statement:

    result = VALUE abaptxt255_tab(
FOR s_line IN it_line
( line = process_line( s_line-source ) ) ).

But I don't find anything strange in it. I don't have a 740 system which I can use to test it though. But, as far as I know, this is a valid 740 statement.


Another example is this:

Check failure on line 58 in src/zcl_timem_gui.clas.abap

 <https://github.com/abapinho/abapTimeMachine/pull/129/checks?check_run_id=12027688923>
abaplint
/ abaplint

Class or type "zcl_timem_gui_handler" not found
https://rules.abaplint.org/check_syntax
related to this line of code:

    DATA(handler) = NEW zcl_timem_gui_handler( me ).

And, again, I don't see anything wrong here.

The linter is probably right but I'm having a hard time understanding these results. Can you please point me to how I can figure these out?

Thanks!


On 15 Mar 2023, at 17:16, Lars Hvam ***@***.***> wrote:


Closed #90 <https://github.com/abapinho/abapTimeMachine/pull/90>.

**Comment by nununo** [comment]
Hi Lars,

I am finally having a little time to dedicate to abapTimeMachine. I noticed you closed this so I replicated it in another branch so that I can go through the list of linter errors and deal with them. But to be honest I'm having a hard time making sense of any of them.

Here it is: https://github.com/abapinho/abapTimeMachine/pull/129/files?diff=unified&w=0

None of them seem to make sense to me, though.
I wonder if I'm doing something wrong. For example, the very first one says this:

Check failure on line 140 in src/zcl_timem_diff.clas.abap
Statement does not exist in ABAPv740sp02(or a parser error), "result"
https://rules.abaplint.org/parser_error

about this statement:

```abap
result = VALUE abaptxt255_tab(
  FOR s_line IN it_line
  ( line = process_line( s_line-source ) ) ).
```

But I don't find anything strange in it. I don't have a 740 system which I can use to test it though. But, as far as I know, this is a valid 740 statement.


Another example is this:

Check failure on line 58 in src/zcl_timem_gui.clas.abap
Class or type "zcl_timem_gui_handler" not found
https://rules.abaplint.org/check_syntax

related to this line of code:

```abap
DATA(handler) = NEW zcl_timem_gui_handler( me ).
```
Again, I don't see anything wrong here.

The linter is probably right but I'm having a hard time understanding these results. Can you please point me to how I can figure these out?

Thanks!

**Pull request closed without merging**
